name: sentence_splitter
description: Dart library for splitting strings into sentences via a stream or iterator. 
version: 0.0.1
repository: https://github.com/D-James-GH/sentence_splitter.git

environment:
  sdk: ^3.9.2


dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
